const cfg = window.ZEN_CONFIG || {}; const storageKey='zen_bilijar_reservations'; const sessionKey='zen_bilijar_admin_auth';
function normalizeStatus(value){const v=(value||'').toLowerCase();if(v==='confirmed'||v==='potvrdjeno'||v==='потврђено')return 'потврђено';if(v==='rejected'||v==='odbijeno'||v==='одбијено')return 'одбијено';if(v==='cancelled'||v==='otkazano'||v==='отказано')return 'отказано';return 'на чекању';}
function getStoredReservations(){try{return JSON.parse(localStorage.getItem(storageKey)||'[]');}catch{return [];}}
function setStoredReservations(items){localStorage.setItem(storageKey,JSON.stringify(items));}
async function apiRequest(action,payload={}){if(cfg.apiBase){const response=await fetch(cfg.apiBase,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});return response.json();}const list=getStoredReservations();if(action==='adminList')return {ok:true,reservations:list,mode:'local'};if(action==='updateReservationStatus'){const updated=list.map(item=>item.code===payload.code?{...item,status:payload.status}:item);setStoredReservations(updated);return {ok:true,reservations:updated,mode:'local'};}if(action==='deleteReservation'){const updated=list.filter(item=>item.code!==payload.code);setStoredReservations(updated);return {ok:true,reservations:updated,mode:'local'};}return {ok:false,message:'Непозната акција.'};}
function badgeClass(status){const s=normalizeStatus(status);if(s==='потврђено')return 'badge confirmed';if(s==='одбијено')return 'badge rejected';if(s==='отказано')return 'badge cancelled';return 'badge pending';}
function showResult(el,text,type){el.textContent=text;el.className=`result-box ${type}`;el.classList.remove('hidden');}
function isLoggedIn(){return sessionStorage.getItem(sessionKey)==='1';}
function setLoggedIn(value){if(value)sessionStorage.setItem(sessionKey,'1');else sessionStorage.removeItem(sessionKey);}
function toggleView(){document.getElementById('adminLoginSection').classList.toggle('hidden',isLoggedIn());document.getElementById('adminPanelSection').classList.toggle('hidden',!isLoggedIn());}
function renderRows(items){const tbody=document.getElementById('adminTableBody');const selectedDate=document.getElementById('filterDate').value;const selectedStatus=document.getElementById('filterStatus').value;const filtered=items.filter(item=>{const byDate=selectedDate?item.date===selectedDate:true;const byStatus=selectedStatus?normalizeStatus(item.status)===selectedStatus:true;return byDate&&byStatus;});if(!filtered.length){tbody.innerHTML='<tr><td colspan="8">Нема резервација за изабрани филтер.</td></tr>';return;}tbody.innerHTML=filtered.map(item=>`<tr><td>${item.code}</td><td>${item.fullName||''}</td><td>${item.phone||''}</td><td>${item.date||''}</td><td>${item.time||''}</td><td>${item.tableType||''}</td><td><span class="${badgeClass(item.status)}">${normalizeStatus(item.status)}</span></td><td><div class="action-row"><button data-action="потврђено" data-code="${item.code}">Потврди</button><button data-action="одбијено" data-code="${item.code}">Одбиј</button><button data-action="отказано" data-code="${item.code}">Откажи</button><button data-delete="${item.code}">Обриши</button></div></td></tr>`).join('');tbody.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',async()=>{await apiRequest('updateReservationStatus',{code:btn.dataset.code,status:btn.dataset.action});loadReservations();}));tbody.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',async()=>{await apiRequest('deleteReservation',{code:btn.dataset.delete});loadReservations();}));}
async function loadReservations(){const res=await apiRequest('adminList');if(!res.ok)return;document.getElementById('adminModeNotice').textContent=cfg.apiBase?'Панел ради над онлајн базом резервација.':'Панел је у демо режиму и приказује локалне резервације на овом уређају.';renderRows(res.reservations||[]);}
function initLogin(){const form=document.getElementById('adminLoginForm');const result=document.getElementById('adminLoginResult');form.addEventListener('submit',e=>{e.preventDefault();const password=document.getElementById('adminPassword').value;if(password===cfg.adminPassword){setLoggedIn(true);toggleView();loadReservations();}else{showResult(result,'Погрешна лозинка.','error');}});}
function initToolbar(){document.getElementById('refreshAdmin').addEventListener('click',loadReservations);document.getElementById('logoutAdmin').addEventListener('click',()=>{setLoggedIn(false);toggleView();});document.getElementById('filterDate').addEventListener('change',loadReservations);document.getElementById('filterStatus').addEventListener('change',loadReservations);}
initLogin();initToolbar();toggleView();if(isLoggedIn())loadReservations();
