const cfg = window.ZEN_CONFIG || {};
const storageKey = 'zen_bilijar_reservations';
function normalizeStatus(value){const v=(value||'').toLowerCase();if(v==='confirmed'||v==='potvrdjeno')return 'потврђено';if(v==='rejected'||v==='odbijeno')return 'одбијено';if(v==='cancelled'||v==='otkazano')return 'отказано';return 'на чекању';}
function getStoredReservations(){try{return JSON.parse(localStorage.getItem(storageKey)||'[]');}catch{return [];}}
function setStoredReservations(items){localStorage.setItem(storageKey,JSON.stringify(items));}
function generateCode(){return `ZEN-${Math.floor(100000+Math.random()*900000)}`;}
async function apiRequest(action,payload={}){if(cfg.apiBase){const response=await fetch(cfg.apiBase,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});return response.json();}const list=getStoredReservations();if(action==='createReservation'){const item={id:Date.now().toString(),code:generateCode(),fullName:payload.fullName,phone:payload.phone,date:payload.date,time:payload.time,players:payload.players,tableType:payload.tableType,note:payload.note||'',status:'на чекању',createdAt:new Date().toISOString()};list.unshift(item);setStoredReservations(list);return {ok:true,reservation:item,mode:'local'};}if(action==='checkReservation'){const item=list.find(r=>r.code===payload.code&&r.phone===payload.phone);if(!item)return {ok:false,message:'Резервација није пронађена.',mode:'local'};return {ok:true,reservation:item,mode:'local'};}return {ok:false,message:'Непозната акција.',mode:'local'};}
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=value;}
function setHref(id,value){const el=document.getElementById(id);if(el)el.href=value;}
function showBox(el,html,type){el.innerHTML=html;el.className=`result-box ${type}`;el.classList.remove('hidden');}
function initStaticContent(){setText('workHoursText',cfg.workHours||'Сваког дана 14:00–01:00');setText('locationText',cfg.address||'Београд');setText('phoneText',cfg.phone||'+381 64 2637342');setText('addressText',cfg.address||'Београд, преко пута Цветкове пијаце');setHref('phoneLink',`tel:${cfg.phone||'+381642637342'}`);setHref('viberLink',`viber://chat?number=${encodeURIComponent(cfg.phone||'+381642637342')}`);setHref('mailLink',`mailto:${cfg.email||'drlazarevicbg@gmail.com'}`);setHref('mapsLink',cfg.mapsUrl||'https://maps.google.com');document.getElementById('year').textContent=new Date().getFullYear();const modeNotice=document.getElementById('modeNotice');if(modeNotice){modeNotice.textContent=cfg.apiBase?'Сајт је повезан на онлајн систем за резервације.':'Тренутно је укључен демо режим за преглед. За праве онлајн резервације повежи backend.';}}
function initMenu(){const btn=document.getElementById('menuToggle');const nav=document.getElementById('mainNav');if(!btn||!nav)return;btn.addEventListener('click',()=>nav.classList.toggle('open'));nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>nav.classList.remove('open')));}
function initHeroSlider(){const slides=Array.from(document.querySelectorAll('.hero-slide'));if(!slides.length)return;let index=0;setInterval(()=>{slides[index].classList.remove('active');index=(index+1)%slides.length;slides[index].classList.add('active');},4200);}
function initGallery(){const lightbox=document.getElementById('lightbox');const lightboxImage=document.getElementById('lightboxImage');const close=document.getElementById('lightboxClose');document.querySelectorAll('.gallery-item').forEach(item=>item.addEventListener('click',()=>{lightboxImage.src=item.dataset.image;lightbox.classList.remove('hidden');}));close.addEventListener('click',()=>lightbox.classList.add('hidden'));lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.classList.add('hidden');});}
function initReservationForm(){const form=document.getElementById('reservationForm');const result=document.getElementById('reservationResult');if(!form||!result)return;const today=new Date().toISOString().split('T')[0];const dateInput=document.getElementById('date');dateInput.min=today;form.addEventListener('submit',async e=>{e.preventDefault();const submitBtn=form.querySelector('button[type="submit"]');submitBtn.disabled=true;submitBtn.textContent='Слање...';const payload={fullName:form.fullName.value.trim(),phone:form.phone.value.trim(),date:form.date.value,time:form.time.value,players:Number(form.players.value),tableType:form.tableType.value,note:form.note.value.trim()};try{const res=await apiRequest('createReservation',payload);if(res.ok){showBox(result,`<strong>Резервација је послата.</strong><br>Шифра: <strong>${res.reservation.code}</strong><br>Статус: <strong>${normalizeStatus(res.reservation.status)}</strong>`,'success');form.reset();document.getElementById('date').min=today;}else{showBox(result,res.message||'Дошло је до грешке.','error');}}catch{showBox(result,'Резервација није послата. Провери везу са сервером.','error');}finally{submitBtn.disabled=false;submitBtn.textContent='Пошаљи резервацију';}});}
function renderStatusCard(item){return `<strong>Шифра:</strong> ${item.code}<br><strong>Име:</strong> ${item.fullName}<br><strong>Термин:</strong> ${item.date} у ${item.time}<br><strong>Тип:</strong> ${item.tableType}<br><strong>Статус:</strong> ${normalizeStatus(item.status)}`;}
function initStatusForm(){const form=document.getElementById('statusForm');const result=document.getElementById('statusResult');if(!form||!result)return;form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Провера...';try{const res=await apiRequest('checkReservation',{code:form.statusCode.value.trim(),phone:form.statusPhone.value.trim()});if(res.ok){showBox(result,renderStatusCard(res.reservation),'success');}else{showBox(result,res.message||'Резервација није пронађена.','error');}}catch{showBox(result,'Провера статуса није успела.','error');}finally{btn.disabled=false;btn.textContent='Провери статус';}});}
initStaticContent();initMenu();initHeroSlider();initGallery();initReservationForm();initStatusForm();
